services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/hls

  auth:
    build: ./auth
    container_name: auth_server
    network_mode: "host"
