services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
      - "8443:8443"  # Expose HTTPS port
    container_name: rtmp_server
    volumes:
      - ./data:/hls
      - ./rtmp/ssl:/etc/nginx/ssl  # Mount SSL certificates
    networks:
      - vssnet
    restart: always

  auth:
    build: ./auth
    container_name: auth_server
    networks:
      - vssnet
    restart: always

networks:
  vssnet:
    driver: bridge
