services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/hls
    networks:
      - vssnet

  auth:
    build: ./auth
    container_name: auth_server
    networks:
      - vssnet

networks:
  vssnet:
    driver: bridge
