name: Deploy ABP Blazor WASM to Azure Static Web Apps

on:
  push:
    branches: [ Production ]        # ← adjust if your prod branch
  pull_request:
    branches: [ Production ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write               # OIDC login to SWA
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true            # ABP uses submodules

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 1 — *Publish* the WASM client
    - name: Publish WASM client
      run: |
        dotnet publish \
          web_backend/src/web_backend.Blazor.Client/web_backend.Blazor.Client.csproj \
          -c Release -o publish

    # 2 — Upload the static files that dotnet just generated
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_GLACIER_08DCA301E }}
        action: upload 

        production_branch: Production

        # ------------------------------------------------------------------
        #       Paths **inside the runner’s working directory**
        # ------------------------------------------------------------------
        # We already built the site, so point SWA straight at it and
        # skip Oryx’s automatic build.
        app_location:        publish/wwwroot    # <- contains index.html
        skip_app_build:      true               # we built it ourselves
        api_location:        ""                 # no Functions backend

