name: Build and deploy ABP Blazor WebAssembly to Azure Static Web Apps

on:
  push:
    branches:
      - Production
  workflow_dispatch:

jobs:
  build-apihost:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Use .NET 8 as your project targets it

      - name: Install ABP CLI using NuGet directly
        run: |
          dotnet new tool-manifest --force
          dotnet tool install Volo.Abp.Cli --version 8.3.1
          dotnet tool restore
          dotnet abp install-libs
        shell: bash

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./web_backend/src/web_backend.HttpApi.Host

      - name: Generate authserver.pfx
        run: dotnet dev-certs https -v -ep ./authserver.pfx -p Varsity2024

      - name: Upload artifact for apihost
        uses: actions/upload-artifact@v4
        with:
          name: authserver-pfx
          path: ./authserver.pfx

  build-deploy-frontend:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    needs: build-apihost

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install ABP CLI using NuGet directly
        run: |
          dotnet new tool-manifest --force
          dotnet tool install Volo.Abp.Cli --version 8.3.1
          dotnet tool restore
          dotnet abp install-libs
        shell: bash

      - name: Create staticwebapp.config.json
        run: |
          mkdir -p web_backend/src/web_backend.Blazor.Client/wwwroot
          echo '{
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/images/*.{png,jpg,gif,ico}", "/*.{css,js}", "/api/*"]
            },
            "routes": [
              {
                "route": "/*",
                "serve": "/index.html",
                "statusCode": 200
              }
            ],
            "mimeTypes": {
              ".json": "text/json",
              ".woff": "application/font-woff",
              ".woff2": "application/font-woff2"
            }
          }' > web_backend/src/web_backend.Blazor.Client/wwwroot/staticwebapp.config.json

      - name: Publish WASM client
        run: |
          dotnet publish -c Release -o publish
        working-directory: ./web_backend/src/web_backend.Blazor.Client

      - name: Verify publish directory contents
        run: |
          ls -la publish/wwwroot
          if [ -f "publish/wwwroot/staticwebapp.config.json" ]; then
            echo "staticwebapp.config.json exists in the output directory"
          else
            echo "ERROR: staticwebapp.config.json not found in output directory"
            cp web_backend/src/web_backend.Blazor.Client/wwwroot/staticwebapp.config.json publish/wwwroot/
          fi

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_GLACIER_08DCA301E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish/wwwroot"
          output_location: ""
          skip_app_build: true
          api_location: ""
