deploy:
  runs-on: ubuntu-latest
  needs: build
  permissions:
    id-token: write
    contents: read

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
      
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.VSS_CLIENT_ID }}
        tenant-id: ${{ secrets.VSS_TENANT_ID }}
        subscription-id: ${{ secrets.VSS_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'vss-backend-api'
        package: .net-app
