name: Build and deploy ASP.Net Core app to Azure Web App - vss-backend-api

on:
  push:
    branches:
      - Production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build ./web_backend/src/web_backend.HttpApi.Host/web_backend.HttpApi.Host.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./web_backend/src/web_backend.HttpApi.Host/web_backend.HttpApi.Host.csproj -c Release -o myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: myapp
          path: myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.VSS_CLIENT_ID }}
          tenant-id: ${{ secrets.VSS_TENANT_ID }}
          subscription-id: ${{ secrets.VSS_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vss-backend-api'
          package: myapp
